"""
Django settings for todo_list_backend project.

Generated by 'django-admin startproject' using Django 5.1.1.

This file is adapted for Docker (Gunicorn + Nginx) and supports:
- Dev: SQLite (USE_SQLITE=1)
- Prod: AWS RDS Postgres (USE_SQLITE=0 + DB_* env vars, SSL by default)

Docs:
- https://docs.djangoproject.com/en/5.1/
"""
from pathlib import Path
import os

# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------
# Core / Security
# ---------------------------------------------------------------------
DEBUG = os.getenv("DEBUG", "0") == "1"
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    # fallback; замени с реален ключ в .env
    "django-insecure-%0k+7--*nj!=vnk(63xzs1xc-q(37u!cia%+#kgllwi977t1+8",
)

# Позволени хостове (CSV). По подразбиране включвам предишните ти стойности.
ALLOWED_HOSTS = [
    h for h in os.getenv(
        "ALLOWED_HOSTS",
        "34.107.115.96,join.velizar-ganchev-backend.com,localhost,127.0.0.1"
    ).split(",") if h
]

# CSRF trusted origins (CSV, напр. https://api.example.com)
CSRF_TRUSTED_ORIGINS = [
    o for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o
]

# ---------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------
# Ако искаш да разрешиш всички: CORS_ALLOW_ALL_ORIGINS=1
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "0") == "1"

# Иначе — списък от произходи (CSV)
CORS_ALLOWED_ORIGINS = [
    o for o in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:4200,http://127.0.0.1:5500"
    ).split(",") if o
]

# ---------------------------------------------------------------------
# Applications
# ---------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',

    'todo_list',
    'user_auth_app',

    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # corsheaders трябва да е рано в списъка
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'todo_list_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # добави пътища към шаблони при нужда
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'todo_list_backend.wsgi.application'

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
# Dev: USE_SQLITE=1 -> SQLite
# Prod: USE_SQLITE=0 -> Postgres (RDS) с SSL по подразбиране
USE_SQLITE = os.getenv("USE_SQLITE", "0") == "1"

if USE_SQLITE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "join"),
            "USER": os.getenv("DB_USER", "join"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            # напр. mydb.xxxx.eu-central-1.rds.amazonaws.com
            "HOST": os.getenv("DB_HOST", ""),
            "PORT": os.getenv("DB_PORT", "5432"),
            "OPTIONS": {
                # RDS обикновено изисква TLS; 'require' е достатъчно за старт.
                "sslmode": os.getenv("DB_SSLMODE", "require")
            },
        }
    }

# ---------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# ---------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------
LANGUAGE_CODE = os.getenv("LANGUAGE_CODE", "en-us")
TIME_ZONE = os.getenv("TIME_ZONE", "UTC")  # или "Europe/Berlin"
USE_I18N = True
USE_TZ = True

# ---------------------------------------------------------------------
# Static & Media (Nginx ще сервира тези пътища през volumes)
# ---------------------------------------------------------------------
STATIC_URL = "/static/"
# В Docker-compose сме вързали named volume към /static — така collectstatic пише там.
STATIC_ROOT = os.getenv("STATIC_ROOT", "/static")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.getenv("MEDIA_ROOT", "/media")

# Ако искаш допълнителни локални директории за статика при dev, добави ги в .env и разглоби CSV:
# STATICFILES_DIRS = [d for d in os.getenv("STATICFILES_DIRS", "").split(",") if d]

# ---------------------------------------------------------------------
# Default primary key field type
# ---------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------
# DRF
# ---------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/day',
        'user': '5000/day',
        'task-write': '20/day',
    },
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ]
}

# ---------------------------------------------------------------------
# Security (препоръки за продукция; активни само когато DEBUG=False)
# ---------------------------------------------------------------------
if not DEBUG:
    # доверявай се на X-Forwarded-Proto от reverse proxy (Nginx/Load Balancer)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS е добра идея ЕДВА СЛЕД като имаш стабилен TLS
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv(
        "SECURE_HSTS_INCLUDE_SUBDOMAINS", "0") == "1"
    SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "0") == "1"
