# Generated by Django 4.2.1 on 2025-12-07 09:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('user_story', 'User Story'), ('technical_task', 'Technical Task')], default='user_story', max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In Progress'), ('await_feedback', 'Await feedback'), ('done', 'Done')], db_index=True, default='todo', max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('checked', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=20)),
                ('members', models.ManyToManyField(related_name='tasks_as_member', to='user_auth_app.userprofile')),
            ],
            options={
                'ordering': ('-created_at', 'priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todo_list.task')),
            ],
        ),
    ]
